# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ['jekyll-paginate']

# Site settings
title: #"Copacetic"
description: > # this means to ignore newlines until "email:"
   Hello!  My name is AJ, and I like narwhals.  Thanks for dropping by!

email: stuhrenberg.aj@gmail.com
#blog logo
logo: "/assets/images/aj_logo.jpg"
# blog cover
cover: "/assets/images/black_tree.png"

#page cover
page_cover: "/assets/images/path-through-the-woods.png"



name: 'AJ Stuhrenberg'
author: 'AJ Stuhrenberg'
author_image: "/assets/images/aj.jpg"

paginate: 10

url: "http://aj9045.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:


  - icon: envelope-o
    url:  mailto:stuhrenberg.aj@gmail.com
    desc: Here's my email address
    share_url:
    share_title:
    share_link:

  - icon: github
    url:  https://github.com/aj9045
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://linkedin.com/in/ajstuhrenberg
    desc: I'm on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: behance
    url: http://behance.com/aj9045
    desc: Take a look at my Behance portfolio
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/aj9045
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 - icon:	instagram
   url:	https://instagram.com/ajs9045
   desc:
   share_url:
   share_title:
   share_link:


exclude: ['vendor']